name: ds_proj
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.0=py311he1a1d09_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=hc6331ae_3
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.6=h9e52e59_3
  - aws-c-http=0.10.4=hffefcd8_3
  - aws-c-io=0.22.0=h20b9e97_1
  - aws-c-mqtt=0.13.3=he28f3f4_6
  - aws-c-s3=0.8.6=ha4cb493_5
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.34.4=hc2cf59f_0
  - aws-sdk-cpp=1.11.606=h296c955_4
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py311h3e6a449_4
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - catalogue=2.0.10=py311h1ea47a8_2
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh7428d3b_0
  - cloudpathlib=0.23.0=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - confection=0.1.5=pyhecae5ae_0
  - contourpy=1.3.3=py311h3fd045d_2
  - cpython=3.11.14=py311hd8ed1ab_1
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=he0c23c2_0
  - cuda-nvrtc=12.9.86=he0c23c2_0
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.13.1.26=h32ff316_0
  - curated-tokenizers=0.0.9=py311he4ec789_4
  - curated-transformers=0.1.1=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cymem=2.0.11=py311h3e6a449_1
  - cython-blis=1.3.0=py311h0a17f05_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=4.2.0=pyhcf101f3_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py311hdf60d3a_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h5f2951f_0
  - hf-xet=1.1.10=py310h63875d3_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_accelerate=1.4.0=py311haa95532_0
  - huggingface_hub=0.35.3=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - kiwisolver=1.4.9=py311h275cad7_1
  - krb5=1.21.3=hdf4eb48_0
  - langcodes=3.4.1=pyhd8ed1ab_1
  - language-data=1.3.0=pyhff2d567_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=21.0.0=h58cbc4c_8_cuda
  - libarrow-acero=21.0.0=h7d8d6a5_8_cuda
  - libarrow-compute=21.0.0=h2db994a_8_cuda
  - libarrow-dataset=21.0.0=h7d8d6a5_8_cuda
  - libarrow-substrait=21.0.0=hf865cc0_8_cuda
  - libblas=3.9.0=28_h576b46c_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=28_h7ad3364_mkl
  - libclang13=21.1.3=default_ha2db4b5_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.9.1.4=he0c23c2_0
  - libcudnn=9.13.1.26=hca898b4_0
  - libcudnn-dev=9.13.1.26=hca898b4_0
  - libcudss=0.7.0.20=hca898b4_1
  - libcufft=11.4.1.4=he0c23c2_0
  - libcurand=10.3.10.19=he0c23c2_0
  - libcurl=8.14.1=h88aaa65_0
  - libcusolver=11.7.5.82=hac47afa_1
  - libcusparse=12.5.10.65=hac47afa_1
  - libdeflate=1.24=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.86.0=h5f26cbf_0
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h04afb49_0
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=28_hacfb0e4_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmagma=2.9.0=hb6a17ea_3
  - libnvjitlink=12.9.86=he0c23c2_1
  - libparquet=21.0.0=h24c48c9_8_cuda
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.08.12=h0eb2380_1
  - libsentencepiece=0.2.1=hea14dff_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h550210a_0
  - libtorch=2.8.0=cuda128_mkl_h0cdabd9_301
  - libutf8proc=2.11.0=h0b34c2f_0
  - libuv=1.51.0=hfd05255_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.0=ha29bfb0_1
  - libxml2-16=2.15.0=h06f855e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - lz4-c=1.10.0=h2466b09_1
  - marisa-trie=1.2.1=py311h3e6a449_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.7=py311h1ea47a8_0
  - matplotlib-base=3.10.7=py311h1675fdf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2024.2.2=h57928b3_15
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py311h3f79411_0
  - multiprocess=0.70.16=py311he736701_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - murmurhash=1.0.13=py311h5dfdfe8_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nltk=3.9.2=pyhcf101f3_1
  - numpy=2.3.3=py311h80b3fa1_0
  - openjpeg=2.5.4=h24db6dd_0
  - openpyxl=3.1.5=py311h4d8bf61_2
  - openssl=3.5.4=h725018a_0
  - optree=0.17.0=py311h3fd045d_1
  - orc=2.2.1=h7414dfc_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h26a3c52_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - preshed=3.0.9=py311hda3d55a_2
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h5082efb_0
  - protobuf=6.31.1=py311heca59f8_2
  - psutil=7.1.0=py311h3485c13_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py311h1ea47a8_1
  - pyarrow-core=21.0.0=py311h819ed09_1_cuda
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh6a1d191_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.2=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py311hf51aa87_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py311hf70c7b4_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h30ce641_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.11.14=hd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py311h2f2c37c_0
  - python_abi=3.11=6_cp311
  - pytorch=2.8.0=cuda128_mkl_py311_h46abf5f_301
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.3=py311h3f79411_0
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_0
  - re2=2025.08.12=ha104f34_1
  - regex=2025.9.18=py311h3485c13_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.6.2=py311h18438d6_1
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - scipy=1.16.2=py311h9a1c30b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sentencepiece=0.2.1=h4d92249_0
  - sentencepiece-python=0.2.1=py311hb993d29_0
  - sentencepiece-spm=0.2.1=hea14dff_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - smart-open=7.3.1=h08b120a_0
  - smart_open=7.3.1=pyhcf101f3_0
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - spacy=3.8.7=py311h287a515_0
  - spacy-alignments=0.9.2=py311h9468d6e_0
  - spacy-curated-transformers=0.3.0=pyhd8ed1ab_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - spacy-model-en_core_web_sm=3.8.0=pyhd8ed1ab_0
  - spacy-model-en_core_web_trf=3.8.0=pyh55bf090_0
  - spacy-transformers=1.1.9=pyhd8ed1ab_0
  - srsly=2.5.1=py311hda3d55a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h17033d2_1
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=h18a62a1_3
  - thinc=8.3.6=py311h05ac4f6_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_2
  - tokenizers=0.13.3=py311h91c4a10_0
  - tornado=6.5.2=py311h3485c13_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.24.0=pyhd8ed1ab_0
  - typer=0.19.2=pyhef33e25_0
  - typer-slim=0.19.2=pyhcf101f3_0
  - typer-slim-standard=0.19.2=h6e3bb38_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - ujson=5.11.0=py311h5dfdfe8_1
  - unicodedata2=16.0.0=py311h3485c13_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wasabi=1.1.3=pyhd8ed1ab_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - weasel=0.4.1=pyhd8ed1ab_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py311h3485c13_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xxhash=0.8.3=hbba6f48_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.20.1=py311h5082efb_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py311hf893f09_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - branca==0.8.2
      - folium==0.20.0
      - geographiclib==2.1
      - geopy==2.4.1
      - xyzservices==2025.10.0
